service: facebook-messenger-bot

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: us-east-1

  environment:
    VERIFY_TOKEN: 'areallylongtoken'
    ACCESS_TOKEN: 'EAAe0WJTGzlMBADqq89xDiIzXPp6eBfekz45wsuhFY2aj4nEHWMxTypbEuQnTa4NKNFUqw7ZB1ZBDfiQuqtRfptWXcSjXgOS613MTL0CIwhT54yPLRxcyMattD2JzO8gBn9rWvZCNRdaagZA8N3KZC2XcCePQgaQnGKdNPzLubIgZDZD'

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: webhook
          method: GET
          integration: lambda
      - http:
          path: webhook
          method: post
          integration: lambda

